import = ["~/dotfiles/alacritty/themes/catppuccin.toml"]

[shell]
  program = "/opt/homebrew/bin/bash"
  args = ['-l']

# Alacritty Configuration in TOML

# Window dimensions (changes require restart)
[window]
  dimensions = { columns = 180, lines = 60}
  opacity = 0.9
  blur = true
  position = {x = 100, y = 100 }
  padding = { x = 10, y = 20}
  decorations = "None"
  option_as_alt = "OnlyLeft" # Needed to make option act as alt to provide commands
  startup_mode = "SimpleFullscreen"

# Font configuration
[font]
  # Specify the font family and style
  normal = { family = "Hack Nerd Font Mono", style = "Regular" } # Ensure this font is installed
  size = 13
  bold = { family = "Hack Nerd Font Mono", style = "Bold" } # Ensure this font is installed
  italic = { family = "Hack Nerd Font Mono", style = "Italic" } # Ensure this font is installed

# Cursor configuration
[cursor]
  style = { shape = "Beam", blinking = "on" }

# Scrollback buffer size (number of lines)
[scrolling]
  history = 10000
  multiplier = 2

[mouse]

[keyboard]
  bindings = [
    {key = "T", mods = "Command", action = "None"}
  ]