import = ["~/dotfiles/alacritty/themes/catppuccin.toml"]

[shell]
  program = "/opt/homebrew/bin/bash"
  args = ['-l']

# Alacritty Configuration in TOML

# Window dimensions (changes require restart)
[window]
  dimensions = { columns = 160, lines = 40}
  opacity = 0.99
  position = { y = 0 }
  padding = { x = 20, y = 20}
  # startup_mode = "Fullscreen"

# Font configuration
[font]
  # Specify the font family and style
  normal = { family = "Hack Nerd Font Mono", style = "Regular" } # Ensure this font is installed
  size = 13
  bold = { family = "Hack Nerd Font Mono", style = "Bold" } # Ensure this font is installed
  italic = { family = "Hack Nerd Font Mono", style = "Italic" } # Ensure this font is installed

# Cursor configuration
[cursor]
  style = { shape = "Beam", blinking = "on" }

# Scrollback buffer size (number of lines)
[scrolling]
  history = 10000
  multiplier = 2

[mouse]